# {{=<% %>=}}
---
apiVersion: deployment.krateo.io/v1alpha1
kind: TerraformCloud
metadata:
  name: <%#norm%>{{name}}<%/norm%>-terraform-cloud
spec:
  owner: Andrea Grillo
  title: <% name %>
  description: Terraform Cloud App Deployment
  icon: "fa-solid fa-fire"
  tags:
    - terraform
    - template
    - krateo
    - cloud
  links:
    - url: https://github.com/<% organizationName %>/<% owner %>-terraform-cloud-<%#norm%>{{name}}<%/norm%>
      title: <% organizationName %>/<% owner %>-terraform-cloud-<%#norm%>{{name}}<%/norm%>
      icon: "fa-brands fa-git"
  plugins:
    - name: resources
      value: <%#norm%>{{name}}<%/norm%>-terraform-cloud
      type: argocd
      icon: fa-solid fa-diagram-project
      endpointName: argocd
    - name: documentation
      values:
        - "[<% organizationName %>][<% owner %>-terraform-cloud-<%#norm%>{{name}}<%/norm%>]README.md"
      type: doc
      icon: fa-solid fa-book
      endpointName: <% destinationEndpoint.friendlyName %>
    - name: kubernetes
      value: deploymentId
      type: kubernetes
      icon: fa-brands fa-docker
    - name: pipelines
      values:
        - "[<% organizationName %>][<% owner %>-terraform-cloud-<%#norm%>{{name}}<%/norm%>]Build Docker image for every commit"
      type: pipeline
      icon: fa-solid fa-person-running
      endpointName: <% destinationEndpoint.friendlyName %>
  values:
    organizationName: <% organizationName %>
    repositoryName: <% owner %>-terraform-cloud-<%#norm%>{{name}}<%/norm%>
    destinationApiUrl: <% destinationEndpoint.target %>
    description: Infrastructure as Code Everywhere
    endpointName: <% destinationEndpoint.friendlyName %>
    namespace: krateo-system
    terraformOrganization: <% terraformOrganization %>
    fromRepo:
      schema: https
      organizationName: <% organizationName %>
      repositoryName: krateo-template-terraform-cloud
    toRepo:
      schema: https
      organizationName: <% organizationName %>
      repositoryName: <% owner %>-terraform-cloud-<%#norm%>{{name}}<%/norm%>
      apiUrl: https://api.github.com
  # for editing purposes
  templateName: krateo-terraformcloud
  flat:
    name: <% name %>
    terraformOrganization: <% terraformOrganization %>
    organizationName: <% organizationName %>
    destinationEndpoint: <% destinationEndpoint.friendlyName %>
